CREATE TABLE MEASUREMENT(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(12),
    TEMPERATURE REAL,
    HUMIDITY REAL,
    PRESSURE INT,
    MAC VARCHAR(24),
    MOVEMENTCOUNTER INT,
    DATE TIMESTAMP
)



